name: Deploy Website to cPanel (Rumah Web)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 🔨 Install dependencies & Build
        run: |
          npm install
          CI=false npm run build
        # WAJIB ADA: Biar koneksi API & WA di frontend tidak putus
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_OFFICE_WHATSAPP: ${{ secrets.VITE_OFFICE_WHATSAPP }}
          VITE_PHONE_SANDI: ${{ secrets.VITE_PHONE_SANDI }}
          VITE_PHONE_FRADIYA: ${{ secrets.VITE_PHONE_FRADIYA }}
          VITE_PHONE_YUANITA: ${{ secrets.VITE_PHONE_YUANITA }}
          VITE_PHONE_DARUS: ${{ secrets.VITE_PHONE_DARUS }}

      # Menggunakan action yang lebih stabil untuk cPanel Rumahweb
      - name: 📂 Deploy via FTP to cPanel
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./dist/
          # Cukup gunakan ./ karena akun FTP sudah mengarah ke public_html
          remoteDir: ./
          options: "--verbose"